Sprint15 add multiple likelihood posterior
CUQI-DTU/CUQIpy pull request #151
Opened 2022-12-03 09:42 UTC by nabriis

Closes #123

2022-12-03 21:15 UTC, nabriis commented
Hi @amal-ghamdi, I finished adding the new MultipleLikelihoodPosterior class. I also added a HowTo for defining Posteriors as I felt this was relevant now with this class.

2022-12-05 09:20 UTC, amal-ghamdi requested changes
Thank you @nabriis. The PR is really great! I have only few comments.

2022-12-05 09:20 UTC, amal-ghamdi commented on cuqi/distribution/_joint_distribution.py
> +        """ Return the likelihoods that make up the posterior. """
```suggestion
        """ Return the likelihoods of the posterior. """
```

2022-12-05 09:20 UTC, amal-ghamdi commented on cuqi/distribution/_joint_distribution.py
> +            grad += likelihood.gradient(*args, **kwargs)
really nice :)

2022-12-05 09:20 UTC, amal-ghamdi commented on demos/howtos/posterior.py
> +"""
I loved this how to! very informative.

2022-12-05 09:20 UTC, amal-ghamdi commented on demos/tutorials/multiple_likelihoods.py
> +# We see that in this case we obtain a :class:`MultipleLikelihoodPosterior`
`MultipleLikelihoodPosterior` to be changed if we change the class name

2022-12-05 09:20 UTC, amal-ghamdi commented on demos/tutorials/multiple_likelihoods.py
> -samples.geometry=theta.geometry
yes 👍!

2022-12-14 17:41 UTC, amal-ghamdi approved these changes
Thank you @nabriis for your updates and improving the robustness of this feature. I just added a minor documentation comment and I have one last thought about the class name. SingleVariablePosterior gives a sense that it is more of a special case of the posterior, not a generalization. But I leave it to you and @jakobsj if you think we should update the name or keep it for now.

Looks great to me!

2022-12-14 17:41 UTC, amal-ghamdi commented on cuqi/distribution/_joint_distribution.py
> +    """ A posterior distribution for a single random variable. There can be multiple likelihoods and priors.
```suggestion
    """ A posterior distribution for a single (scalar or vector) random variable. There can be multiple likelihoods and priors.
```

2022-12-14 17:41 UTC, amal-ghamdi commented on cuqi/distribution/_joint_distribution.py
> +        return sum(density.gradient(*args, **kwargs) for density in self._densities)
👍  :)

2023-01-26 13:33 UTC, jakobsj requested changes
Thank you for adding this great new feature. After discussing it (again) today, I am happy to see it merged, with a few minor changes and as discussed renaming back to `MultipleLikelihoodPosterior`.

We discussed this PR as step toward a new zoo of Posterior classes with specific purpose and behaviors, probably organized into a subclass structure with a generic (Joint?)Posterior at the top, from which branches of dedicated subclasses could be formed, such MultipleLikelihoodPosterior and from that perhaps the existing Posterior as a special case of single likelihood. This would likely involve a JointPosterior and we should decide on systematic naming conventions. Please before merging this PR could you create one or more issues (likely not labelled ready) to capture this idea.

2023-01-26 13:33 UTC, jakobsj commented on cuqi/distribution/_joint_distribution.py
> +    """ A posterior distribution for a single random variable. There can be multiple likelihoods and priors.
Only multiple likelihoods, not priors?

2023-01-26 13:33 UTC, jakobsj commented on cuqi/distribution/_joint_distribution.py
> +    it is a joint distribution with multiple likelihoods and priors. This is mostly
Multiple likelihoods, not multiple priors?

2023-01-26 13:33 UTC, jakobsj commented on demos/howtos/posterior.py
> +How to define a Posterior distribution
Great howto with gradually increasing complexity.  For naming of the file, "posterior.py" could suggest it being a posterior class or module, and does not describe what the howto does with a posterior. I suggest (in general I suppose)  including a verb in the filename, such as "defining_posteriors", "setting_up_a_posterior", or similar.

2023-01-26 13:33 UTC, jakobsj commented on cuqi/distribution/_joint_distribution.py
> +class SingleVariablePosterior(JointDistribution, Distribution):
In our discussion today we agreed to rename back to `MultipleLikelihoodPosterior`, which makes it clearer what this class is, that it is a more general form of posterior.

2023-01-27 21:03 UTC, nabriis commented
Hi @jakobsj thanks for the comments!

2023-01-30 15:31 UTC, jakobsj approved these changes
Looks good!

2023-01-30 16:07 UTC, merged