Add Jacobian matrix option to Model
CUQI-DTU/CUQIpy pull request #216
Opened 2023-04-22 08:09 UTC by nabriis

Closes #204

2023-04-24 08:02 UTC, jakobsj requested changes
Overall looks good, couple of small requests mainly to add one or more small examples to help convey how to specify gradient/Jacobian, as the current description while accurate may be aided by more concrete instructions such as an example.

2023-05-03 05:56 UTC, amal-ghamdi approved these changes
LGTM!

2023-05-03 19:24 UTC, amal-ghamdi commented on cuqi/model/_model.py
@nabriis, following our discussion today,  here is a suggestion on how to update PDEModel initializer:

Change it from:
```python
    def __init__(self, PDE, range_geometry, domain_geometry):
        #....
        if not isinstance(PDE,cuqi.pde.PDE):
            raise ValueError("PDE needs to be a cuqi PDE.")
        super().__init__(self._forward_func, range_geometry, domain_geometry)
        self.pde = PDE
        if hasattr(self.pde, "gradient_wrt_parameter"):
            self._gradient_func = self.pde.gradient_wrt_parameter
```

To probably something like 
```python
    def __init__(self, PDE, range_geometry, domain_geometry):
        #....
        if not isinstance(PDE,cuqi.pde.PDE):
            raise ValueError("PDE needs to be a cuqi PDE.")
        if hasattr(self.pde, "gradient_wrt_parameter"):
            gradient = PDE.gradient_wrt_parameter
        if hasattr(self.pde, "jacobian_wrt_parameter"):
            jacobian = PDE.jacobian_wrt_parameter
        super().__init__(self._forward_func, range_geometry, domain_geometry, gradient, jacobian)
        self.pde = PDE

```

2023-05-03 19:25 UTC, amal-ghamdi reviewed
I added a comment about the PDEModel initializer

2023-05-03 19:28 UTC, amal-ghamdi requested changes
I am just adding request changes to keep track of the comment about the PDEModel initializer :)

2023-05-14 20:28 UTC, nabriis reviewed
Took the comments into account @amal-ghamdi and @jakobsj. Thanks again.

2023-05-14 20:28 UTC, nabriis commented on cuqi/model/_model.py
> +    jacobian : callable function, optional
Added the example. Hope it helps

2023-05-14 20:28 UTC, nabriis commented on cuqi/model/_model.py
Thanks. I added something akin to this.

2023-05-14 20:28 UTC, nabriis commented on cuqi/model/_model.py
> +            raise TypeError("Jacobian needs to be callable function of some kind")
Revised.

2023-05-24 07:25 UTC, jakobsj approved these changes
Thank you for incorporating the suggestions. It looks great, in particular the detailed example is very helpful.

2023-05-24 09:01 UTC, merged