Fix 277 update readme and landing page
CUQI-DTU/CUQIpy pull request #285
Opened 2023-10-04 22:43 UTC by nabriis

Closes #277

2023-10-05 21:04 UTC, jakobsj requested changes
Looks very good! A few small comments. The ones to the readme probably also apply to the index.rst.

2023-10-05 21:04 UTC, jakobsj commented on cuqi/data/_data.py
> +    if grayscale:
What's going on here - I thought this was done in another PR?

2023-10-06 14:46 UTC, nabriis commented on README.md
> +## 🔌 Plugins
Done

2023-10-06 14:46 UTC, nabriis commented on README.md
> +## 🌟 Contributors
Created issue #286

2023-10-06 14:48 UTC, amal-ghamdi approved these changes

2023-10-06 15:00 UTC, merged