change get_components to regular method
CUQI-DTU/CUQIpy pull request #302
Opened 2023-10-15 18:41 UTC by chaozg

This PR fixed #47 by changing `get_components` from a class method to a regular/instance method.

The following snippet is used to check if the returned components are as expected:
```Python
# %%
import cuqi
from cuqi.testproblem import Deconvolution1D
import matplotlib.pyplot as plt

# %% setup problems
dim = [32, 128]
phantom = ["pc","bumps"]
noise_type = ["Gaussian","ScaledGaussian"]
noise_std = [0.05, 0.0001]

# Test problems
prob0 = Deconvolution1D(
    dim = dim[0],
    phantom=phantom[0],
    noise_type=noise_type[0],
    noise_std = noise_std[0]
)
prob1 = Deconvolution1D(
    dim = dim[1],
    phantom=phantom[1],
    noise_type=noise_type[1],
    noise_std = noise_std[1]
)

# %% use get_components to extract information
A0, y_data0, probInfo0 = prob0.get_components()
A1, y_data1, probInfo1 = prob1.get_components()

# check if the extraced y_datax are as expected
plt.figure()
y_data0.plot()
plt.figure()
y_data1.plot()
```
and the plots are like:
![image](https://github.com/CUQI-DTU/CUQIpy/assets/69794131/6459c131-4b80-4066-be3b-24e6c1b0fe37)
and 
![image](https://github.com/CUQI-DTU/CUQIpy/assets/69794131/be987b8a-0a7b-4e11-8ea0-676fa4058302)

2023-10-15 19:27 UTC, chaozg commented
The failure is due to a check at `/tests/test_bayesian_inversion.py`

```Python
def test_Bayesian_inversion_hierarchical(TP_type: BayesianProblem, phantom: str, priors: Dict[str, Density], Ns: int):
    # Load model + data from testproblem library
    A, y_data, probInfo = TP_type.get_components(dim=priors[0].dim, phantom=phantom)
```
I think I need some advice on how to solve this problem.

2023-10-24 18:32 UTC, nabriis requested changes
Thank you @chaozg. The current changes look great and the actual change to the BayesianProblem class is exactly as I had hoped!

I would advice using a search tool like the search function inside visual studio code to find all cases of "get_components" to ensure to did not miss any. For example there should be some inside the docs/ folder also.

In addition, I think we should briefly discuss at the stand up what the best new syntax is, e.g.:
```python
A, y_obs, info = Deconvolution1D(dim=128).get_components() # Current with this case
A, y_obs, info = Deconvolution1D(dim=128).components # Perhaps this more concice syntax?
```

Finally, considering that we call it "components" of the BayesianProblem. It may be worth it to ensure we actually include all the components from the problem. We could do this by adding more things to the ProblemInfo class. This could e.g. be the likelihood and prior also. I note this could be added as a new issue and PR as to not polute this one too much

2023-10-24 20:56 UTC, chaozg commented
> I would advice using a search tool like the search function inside visual studio code to find all cases of "get_components" to ensure to did not miss any. For example there should be some inside the docs/ folder also.

@nabriis Thanks for the hint, and yes I just did as you suggested and confirm that all files including `get_components` run well now.
Meanwhile, I want to make an off-topic note that `demos/ExploreTestProblems` mentions `ParBeamCT2D`, which seems not available in CUQIpy's current release:
```Python
elif testprob == 5:
    model, data, probInfo = ParBeamCT2D(im_size=(50,50),det_count=60, proj_type="line").get_components() #cuda
```
Anyhow, I also made changes according here, i.e., moving arguments `im_size=(50,50),det_count=60, proj_type="line"` from `get_components` to the class constructor.

2023-10-25 05:17 UTC, amal-ghamdi reviewed
Thank you Charlie for this update! The PR looks good 👍 I just had one minor suggested change. Also thank you for creating issue #https://github.com/CUQI-DTU/CUQIpy-CIL/issues/28 , would you please create a similar one for CUQIpy-FEniCS. Thank you.

2023-10-25 05:17 UTC, amal-ghamdi commented on demos/howtos/Defining_Posterior.py
> +B, d_obs, _ = cuqi.testproblem.Deconvolution1D(PSF="Defocus",noise_std=0.02).get_components()
```suggestion
B, d_obs, _ = cuqi.testproblem.Deconvolution1D(PSF="Defocus", noise_std=0.02).get_components()
```

2023-10-25 05:23 UTC, amal-ghamdi commented
> ```python
> ParBeamCT2D
> ```

That's a good catch! I think this test problem was moved to CIL `cuqipy_cil.testproblem.ParallelBeam2D`, @jakobsj and @nabriis might be able to confirm if this is the case 😊

2023-10-25 07:21 UTC, jakobsj commented
I parked the potential renaming of get_components() as a separate issue here https://github.com/CUQI-DTU/CUQIpy/issues/303

2023-10-25 09:10 UTC, nabriis commented
> > I would advice using a search tool like the search function inside visual studio code to find all cases of "get_components" to ensure to did not miss any. For example there should be some inside the docs/ folder also.
> 
> @nabriis Thanks for the hint, and yes I just did as you suggested and confirm that all files including `get_components` run well now. Meanwhile, I want to make an off-topic note that `demos/ExploreTestProblems` mentions `ParBeamCT2D`, which seems not available in CUQIpy's current release:
> 
> ```python
> elif testprob == 5:
>     model, data, probInfo = ParBeamCT2D(im_size=(50,50),det_count=60, proj_type="line").get_components() #cuda
> ```
> 
> Anyhow, I also made changes according here, i.e., moving arguments `im_size=(50,50),det_count=60, proj_type="line"` from `get_components` to the class constructor.

Hello @chaozg. Thanks for updating that. I believe there must be other areas where get_components is used. Two that I noticed are in the index.rst file for online docs and in the example docstring for BayesianProblem.  Did you use the search functionality to find all uses of get_components?

2023-10-25 09:11 UTC, nabriis reviewed
See comment above. Seems more areas need to be updated.

2023-10-25 15:01 UTC, nabriis approved these changes
Thank you @chaozg. The PR LGTM now! 🎉 

Thank you for sticking through the review process. I think this change will make the testproblems much easier to use for the users! Very important.

2023-10-27 06:35 UTC, amal-ghamdi approved these changes
Thank you @chaozg for the updates! LGTM

2023-10-27 06:41 UTC, merged