Find valid samplers
CUQI-DTU/CUQIpy pull request #446
Opened 2024-06-28 07:21 UTC by jeverink

Added a method that returns a list of all samplers that should pass validate_target.

Also fixes a bug where the two proposal based samplers are valid for implicit distribution.
This fix assumes that implicit distributions return NaN when logd is called, which is currently the case.
(Charlie edited: the above is for correctly identifying `CWMH` and `MH` as __invalid__ for targets with implicit priors)

Note: I have not checked whether the whether the returned samplers to actually work, so the added tests might not be proper.

closed #447

2024-06-28 07:57 UTC, chaozg commented
This is excellent! @jeverink

2024-06-30 21:50 UTC, nabriis commented
Looks great @jeverink. Will discuss with team on where to put the utility method and its name. But fantastic idea!

2024-07-01 08:34 UTC, chaozg requested changes
Hi @jeverink , this PR will definitely improve a user's experience with CUQIpy and I'm very happy to see such a neat implementation and so extensive test cases. After a brief group discussion with @jakobsj and @nabriis , the only suggestion I have so far is to put `find_valid_samplers ` to a more proper place, like `cuqi/experimental/mcmc/_utilities.py`.

2024-07-01 09:04 UTC, chaozg approved these changes

2024-07-01 12:12 UTC, jakobsj approved these changes
Great idea and elegant solution! Thanks very much for contributing this utility. Already in great shape so I see no need for any changes.

2024-07-01 12:33 UTC, merged