Remove postfix New (only) from sampler names
CUQI-DTU/CUQIpy pull request #477
Opened 2024-08-17 13:24 UTC by chaozg

2024-08-17 13:32 UTC, nabriis approved these changes
Hi @chaozg. LGTM. I found 2 minor mistakes.

2024-08-17 13:32 UTC, nabriis commented on tests/zexperimental/test_mcmc.py
> -    assert np.allclose(samples_old, samples_new), f"Old: {samples_old[0]}\nNew: {samples_new[0]}"
This seems to be an error

2024-08-17 13:32 UTC, nabriis commented on tests/zexperimental/test_mcmc.py
> -    assert np.allclose(samples_old, samples_new, atol=atol), f"Old: {samples_old}\nNew: {samples_new}"
Also here an error.

2024-08-17 13:41 UTC, chaozg commented on tests/zexperimental/test_mcmc.py
> -    assert np.allclose(samples_old, samples_new), f"Old: {samples_old[0]}\nNew: {samples_new[0]}"
Corrected

2024-08-17 13:41 UTC, chaozg commented on tests/zexperimental/test_mcmc.py
> -    assert np.allclose(samples_old, samples_new, atol=atol), f"Old: {samples_old}\nNew: {samples_new}"
Corrected

2024-08-19 15:28 UTC, amal-ghamdi requested changes
Thank you @chaozg, this is great! 

Just one comment, in the beginning of demo37 there are 2 occurrences in the text for `HybridGibbsNew`. It will be great if you can update that.

```
## HybridGibbsNew
One feature we get from the new sampler design is more flexibility in our Gibbs sampling.
Now we can for example run with sampler instances, which allows us to set parameters and also use all samplers in Gibbs sampling.

We call this new sampler HybridGibbsNew to distinguish it from classical Gibbs sampling.
```

2024-08-19 15:33 UTC, chaozg commented
Thank you, Amal, for noticing that. I just pushed an update.

2024-08-19 15:44 UTC, amal-ghamdi approved these changes
Nice @chaozg, you also spotted the third occurrence 👍

2024-08-20 06:33 UTC, merged