Add 479 experimental module in bayesian problem
CUQI-DTU/CUQIpy pull request #500
Opened 2024-09-01 20:08 UTC by nabriis

Closes #479

2024-09-03 16:09 UTC, amal-ghamdi requested changes
Many thanks @nabriis for this update!! It looks great, I tested it on training notebooks 3 and 4 and the results are below (results are consistent). There is the issue that the output of the sampling progress bar is across so many lines in the experimental case but was good in the legacy case. But I think this is out of the scope of this PR.

I also added few minor comments in the review.

Training Notebook B03 (from the book)
experimental = False (output of sampling progress is nice)

![image](https://github.com/user-attachments/assets/623cfe4c-4ca7-4153-88fd-f7eeebc88c52)

experimental = True  (output of sampling progress is very long)

![image](https://github.com/user-attachments/assets/59efb5f2-7b81-45c3-8fdd-cd8a5a4e09fd)

Training Notebook B04 (from the book)

experimental =False
![image](https://github.com/user-attachments/assets/a411accd-b787-4ca8-a004-f4501e2017fa)
![image](https://github.com/user-attachments/assets/0c2fd030-433a-46b3-b64c-2b3ddd775fb0)

experimental = True

![image](https://github.com/user-attachments/assets/e212b838-903e-4e4e-a317-8a88495e228d)

![image](https://github.com/user-attachments/assets/737ef2f2-f8d2-4901-81e2-14630cc44e1e)

2024-09-03 20:32 UTC, nabriis commented on cuqi/problem/_problem.py
> +    def _determine_sampling_strategy(self, experimental=False):
Yes that sounds good. Perhaps best once we have a clear indication the HybridGibbs is working well with NUTS/MH etc. And likely after #503 is at least merged.

2024-09-03 20:33 UTC, nabriis commented on cuqi/problem/_problem.py
> +            print("Using experimental LinearRTO sampler.")
Done. Good suggestion.

2024-09-03 20:33 UTC, nabriis commented on cuqi/problem/_problem.py
>          print("!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!")
Agreed. Done

2024-09-03 20:34 UTC, nabriis commented on tests/test_bayesian_inversion.py
> +    #else:
Removed. Fixed the issue but forgot to remove the commented code.

2024-09-03 20:34 UTC, nabriis commented
Hi @amal-ghamdi  and @chaozg. Ready for review again.

2024-09-04 08:10 UTC, chaozg approved these changes
Thanks @nabriis . This PR looks very nice and I don't have any suggestions except for the following tiny comments:

- I'm curious if the statement here, "[Most functionality is currently only implemented for this simple case.](https://github.com/CUQI-DTU/CUQIpy/blob/cd99155177420d1f6751bd6cb5c7771718aa6336/cuqi/problem/_problem.py#L130)", is still true with Gibbs, particulary the new HybridGibbs?
- A tiny reminder for the future, we still use the `x0` keyword in `BayesianProblem`, instead of `initial_point`, and this is of course out of the scope of this PR.

2024-09-04 08:42 UTC, amal-ghamdi requested changes
Thanks @nabriis! I add a few suggested changes and added issue #505 to capture the discussion here.

2024-09-04 08:42 UTC, amal-ghamdi commented on cuqi/problem/_problem.py
> +            print("!!! Automatic solver selection is work-in-progress !!!")
```suggestion
            print("!!! Automatic solver selection is a work-in-progress !!!")
```

2024-09-04 08:42 UTC, amal-ghamdi commented on cuqi/problem/_problem.py
> +            print("!!! Automatic solver selection is work-in-progress !!!")
```suggestion
            print("!!! Automatic solver selection is a work-in-progress !!!")
```

2024-09-04 08:42 UTC, amal-ghamdi commented on cuqi/problem/_problem.py
> +        print("!!! Automatic sampler selection is work-in-progress. !!!")
```suggestion
        print("!!! Automatic sampler selection is a work-in-progress. !!!")
```

2024-09-04 08:42 UTC, amal-ghamdi commented on cuqi/problem/_problem.py
> +    def _determine_sampling_strategy(self, experimental=False):
Sounds good, I added issue #505 to capture this

2024-09-04 11:30 UTC, amal-ghamdi approved these changes
LGTM!

2024-09-04 11:31 UTC, merged