Fix issue of accepting invalid proposals
CUQI-DTU/CUQIpy pull request #518
Opened 2024-09-12 17:33 UTC by chaozg

fixed #494

2024-09-12 18:39 UTC, amal-ghamdi approved these changes
Thank you @chaozg! Looks neat and makes sense to me.

2024-09-12 19:05 UTC, nabriis requested changes
Hey @chaozg. Thank you for fixing this issue. Could you somehow, based on the `beta` distribution design a test that runs through our list of samplers, sample e.g. 50 samples, then test if any invalid samples are present? This would catch the problem in future implementations. You can try to uncomment our isnan and isinf cases to check if the test would catch the issue.

You can put the test in zexperimental/test_mcmc.py file. You can use one of the existing lists of samplers that we have as a variable in that file. Then try sampling the beta distribution for each of those samplers and compare and check for invalid.

2024-09-12 20:46 UTC, chaozg commented
Thank @amal-ghamdi and @nabriis for your review.

@nabriis , I just added a test to check
- if MH, ULA, MALA, NUTS work for scaler Beta(0.5,0.5)
- if MH, MH, CWMH, ULA, MALA, NUTS work for vector iid Beta([0.5, 0.5], [0.5,0.5])

I think I just take a simple (but naive) way to create a test function. Any suggestion to improve this test function is welcome : )

2024-09-12 20:53 UTC, chaozg commented
> Hey @chaozg. Thank you for fixing this issue. Could you somehow, based on the `beta` distribution design a test that runs through our list of samplers, sample e.g. 50 samples, then test if any invalid samples are present? This would catch the problem in future implementations. You can try to uncomment our isnan and isinf cases to check if the test would catch the issue.

Yes, test as you suggested and the test case can capture invalid samples, out of bound of [0, 1] in this Beta case.

> 
> You can put the test in zexperimental/test_mcmc.py file. You can use one of the existing lists of samplers that we have as a variable in that file. Then try sampling the beta distribution for each of those samplers and compare and check for invalid.

It seems I can't use the existing samplers as I need to handpick only MH, ULA ,MALA, NUTS for bounded scalar distribution and only MH, CWMH, ULA ,MALA, NUTS for bounded vector distribution. But I might be very wrong here.

2024-09-13 07:49 UTC, nabriis commented on tests/zexperimental/test_mcmc.py
> +        f"Invalid samples accepted for sampler {sampler.__class__.__name__}."
```suggestion
sampler_instances_for_bounded_distribution = [
    cuqi.experimental.mcmc.MH(
        target=cuqi.distribution.Beta(0.5, 0.5),
        initial_point=np.array([0.1]),
        scale=0.1,
    ),
    cuqi.experimental.mcmc.ULA(
        cuqi.distribution.Beta(0.5, 0.5),
        initial_point=np.array([0.1]),
        scale=0.1,
    ),
    cuqi.experimental.mcmc.MALA(
        cuqi.distribution.Beta(0.5, 0.5),
        initial_point=np.array([0.1]),
        scale=0.1,
    ),
    cuqi.experimental.mcmc.NUTS(
        cuqi.distribution.Beta(0.5, 0.5), initial_point=np.array([0.1])
    ),
    cuqi.experimental.mcmc.MH(
        target=cuqi.distribution.Beta(np.array([0.5, 0.5]), np.array([0.5, 0.5])),
        initial_point=np.array([0.1, 0.1]),
        scale=0.1,
    ),
    cuqi.experimental.mcmc.CWMH(
        target=cuqi.distribution.Beta(
            np.array([0.5, 0.5]), np.array([0.5, 0.5])
        ),
        initial_point=np.array([0.1, 0.1]),
        scale=0.1,
    ),
    cuqi.experimental.mcmc.ULA(
        cuqi.distribution.Beta(np.array([0.5, 0.5]), np.array([0.5, 0.5])),
        initial_point=np.array([0.1, 0.1]),
        scale=0.1,
    ),
    cuqi.experimental.mcmc.MALA(
        cuqi.distribution.Beta(np.array([0.5, 0.5]), np.array([0.5, 0.5])),
        initial_point=np.array([0.1, 0.1]),
        scale=0.1,
    ),
    cuqi.experimental.mcmc.NUTS(
        cuqi.distribution.Beta(np.array([0.5, 0.5]), np.array([0.5, 0.5])),
        initial_point=np.array([0.1, 0.1]),
    ),
]

@pytest.mark.parametrize("sampler", sampler_instances_for_bounded_distribution)
def test_if_invalid_sample_accepted(sampler: cuqi.experimental.mcmc.Sampler):
    sampler.sample(50)
    samples = sampler.get_samples().samples
    tol = 1e-8
    assert (
        samples.min() > 0.0 - tol and samples.max() < 1.0 + tol
    ), f"Invalid samples accepted for sampler {sampler.__class__.__name__}."
```

Reformatting suggestion.

2024-09-13 07:55 UTC, chaozg commented
Thank you @nabriis  for the review and also the hint on using vercel black

2024-09-13 08:02 UTC, merged