Regularized Gaussian: TV with Gibbs
CUQI-DTU/CUQIpy pull request #587
Opened 2024-11-22 10:14 UTC by jeverink

Add conjugacy rules for regularized Gaussian with TV regularization

Features:
- [X] Code for counting piecewise constant components of a 1D and 2D array
- [X] Tests for components counting
- [ ] Add conjugacy rules
- [ ] Add tests for conjugacy rules
- [ ] Add regression test for full hierarchical model with TV

2024-11-28 11:35 UTC, jeverink commented
@nabriis , within the `_get_conjugate_parameter` method _conjugate.py, an error is raised when the same parameter is found multiple times. Is there any particular reason for raising this error? Because for the RegularizedGaussian and ModifiedHalfNormal conjugacy pair the parameter will occur twice.

2025-01-13 07:58 UTC, chaozg commented
@nabriis FYR

2025-01-14 17:20 UTC, nabriis commented
> @nabriis , within the `_get_conjugate_parameter` method _conjugate.py, an error is raised when the same parameter is found multiple times. Is there any particular reason for raising this error and not just returning a list to loop over? Because for the RegularizedGaussian and ModifiedHalfNormal conjugacy pair the parameter will occur twice.

This would be a new behavior. I think the error being raised was to be on the safe side. I am reviewing the code now.

2025-01-14 17:33 UTC, nabriis requested changes
Really nice @jeverink! Sorry I missed this PR for this long. I dont have many comments, but I was wondering if you could add clauses to BayesianProblem such that these new added conjugate distributions are supported?

It is around here: https://github.com/jeverink/CUQIpy/blob/4a6ed5f94e5d3a4bf29b0b0bf36b073d1e88ef68/cuqi/problem/_problem.py#L927

2025-01-14 17:33 UTC, nabriis commented on tests/zexperimental/test_mcmc.py
> -    ("gaussian-gamma", "cov", lambda s: s, "Gaussian-Gamma conjugate pair defined via covariance requires `cov` for the `Gaussian` to be: lambda x : 1.0/x for the conjugate parameter"),
To be clear. The removed ones are now supported?

2025-01-14 17:34 UTC, nabriis commented
> > @nabriis , within the `_get_conjugate_parameter` method _conjugate.py, an error is raised when the same parameter is found multiple times. Is there any particular reason for raising this error and not just returning a list to loop over? Because for the RegularizedGaussian and ModifiedHalfNormal conjugacy pair the parameter will occur twice.
> 
> This would be a new behavior. I think the error being raised was to be on the safe side. I am reviewing the code now.

It should be fine to do as you suggest and have done in the code

2025-01-15 08:51 UTC, jeverink commented on tests/zexperimental/test_mcmc.py
> -    ("gaussian-gamma", "cov", lambda s: s, "Gaussian-Gamma conjugate pair defined via covariance requires `cov` for the `Gaussian` to be: lambda x : 1.0/x for the conjugate parameter"),
Yes, the removes ones should now be supported.

2025-01-15 09:38 UTC, jeverink commented
Thanks for the feedback @nabriis ,
I have added the conjugacy with ModifiedHalfNormal to BayesianProblem as you suggested.

2025-01-16 19:00 UTC, chaozg reviewed
Thank you @jeverink for this comprehensive PR, which definitely will lead to many interesting applications of CUQIpy. I just left some questions when I was reading the code.

2025-01-16 19:00 UTC, chaozg commented on cuqi/experimental/mcmc/_conjugate.py
> +            self._conjugatepair = _RegularizedGaussianModifiedHalfNormalPair(self.target)
Just curious if makes sense to consider `MultipleLikelihoodPosterior` here or mention somewhere that `MultipleLikelihoodPosterior` is not supported yet?

2025-01-16 19:00 UTC, chaozg commented on cuqi/experimental/mcmc/_conjugate.py
> +        # Create Gamma distribution and sample
We only set the distribution, no sample here, right?
```suggestion
        # Create Gamma distribution
```

2025-01-16 19:00 UTC, chaozg commented on cuqi/experimental/mcmc/_conjugate.py
> +        return Gamma(shape=m/2 + alpha, rate=.5 * np.linalg.norm(L @ (Ax - b))**2 + beta)
Interesting conjugate relationship. Could you give references to these conjugate relationships, e.g., regularized Gaussian with nonnegativity, l1 and TV constraints? I guess they are from your papers. Could you comment or even put in docstring to make clear which section or equations a reader could look at if they are interested?

2025-01-16 19:00 UTC, chaozg commented on cuqi/experimental/mcmc/_conjugate.py
> +        # Create conjugate distribution and sample
```suggestion
        # Create conjugate distribution
```

2025-01-16 19:00 UTC, chaozg commented on tests/zexperimental/test_mcmc.py
> +                                                        [0.28756339, 0.31439747, 0.29883007, 0.29409678, 0.3142019, 0.28276159, 0.27819533, 0.32371729, 0.24194986, 0.30077088]]))
Interesting, this assertion fails on my machine actually. My sampled `x` is 
```bash
array([[ 2.87563432e-01,  3.14397470e-01,  2.98830065e-01,
         2.92412590e-01,  3.14201898e-01,  2.82761594e-01,
         2.78195333e-01,  3.23706420e-01,  2.41949513e-01,
        -4.84439282e+10],
       [ 2.87563386e-01,  3.14397470e-01,  2.98830065e-01,
         2.94096776e-01,  3.14201898e-01,  2.82761594e-01,
         2.78195333e-01,  3.23717292e-01,  2.41949862e-01,
         3.48007524e+10]])
```
You see the last components of both rows go crazy.

2025-01-17 09:39 UTC, jeverink commented on cuqi/distribution/_modifiedhalfnormal.py
> +    def alpha(self, value):
It can indeed also be an array. I have updated the documentation.

2025-01-17 09:47 UTC, jeverink commented on cuqi/experimental/mcmc/_conjugate.py
> +            self._conjugatepair = _RegularizedGaussianModifiedHalfNormalPair(self.target)
It would require a bit more work to support the `MultipleLikelihoodPosterior`.
When passing a `MultipleLikelihoodPosterior` it currently gives a TypeError that the target should be of type `Posterior`.

2025-01-17 09:55 UTC, jeverink commented on cuqi/experimental/mcmc/_conjugate.py
> +        return Gamma(shape=m/2 + alpha, rate=.5 * np.linalg.norm(L @ (Ax - b))**2 + beta)
I have updated the comments and references.

2025-01-17 09:56 UTC, jeverink commented on tests/zexperimental/test_mcmc.py
> +                                                        [0.28756339, 0.31439747, 0.29883007, 0.29409678, 0.3142019, 0.28276159, 0.27819533, 0.32371729, 0.24194986, 0.30077088]]))
This does not seem like a problem I am able to fix.

2025-01-17 11:55 UTC, chaozg approved these changes
LGTM 👍

2025-01-17 11:55 UTC, chaozg commented on cuqi/experimental/mcmc/_conjugate.py
> +    Section 4 from [2] Everink, Jasper M., Yiqiu Dong, and Martin S. Andersen. "Sparse Bayesian inference with regularized Gaussian distributions." Inverse Problems 39.11 (2023): 115004.
Good!

2025-01-17 11:55 UTC, chaozg commented on tests/zexperimental/test_mcmc.py
> +                                                        [0.28756339, 0.31439747, 0.29883007, 0.29409678, 0.3142019, 0.28276159, 0.27819533, 0.32371729, 0.24194986, 0.30077088]]))
Indeed, this seems due to apple chips

2025-01-20 14:07 UTC, merged