add implementation of _ProductGeometry
CUQI-DTU/CUQIpy pull request #593
Opened 2024-12-02 07:16 UTC by amal-ghamdi

closes #592

2024-12-20 11:30 UTC, nabriis requested changes
Thanks @amal-ghamdi

Looks good. I had some minor comments.

2024-12-20 11:30 UTC, nabriis commented on cuqi/experimental/geometry/_productgeometry.py
> +        """Representation of the product geometry."""
Printing looks a little off?
![image](https://github.com/user-attachments/assets/d11af2b4-8dd5-4744-84e4-7ffbfa155793)
not sure we need this "of the following geometries"

2024-12-20 11:30 UTC, nabriis commented on cuqi/experimental/geometry/_productgeometry.py
> +        List of geometries to be combined into a product geometry.
It seems it should not be a list, but rather comma-seperated arguments.

2024-12-20 11:30 UTC, nabriis commented on cuqi/experimental/geometry/_productgeometry.py
> +        self.geometries = geometries
I suggest adding some error handling to check the input is Geometry

2024-12-20 11:30 UTC, nabriis commented on cuqi/experimental/geometry/_productgeometry.py
> +    def par_dim_list(self):
Maybe we make this one private?

2024-12-20 11:30 UTC, nabriis commented on cuqi/experimental/geometry/_productgeometry.py
> +    def stacked_par_split_indices(self):
Also consider making this private

2024-12-20 11:30 UTC, nabriis commented on cuqi/experimental/geometry/_productgeometry.py
> +    def par2fun(self, *args):
I don't recall if we support args and kwargs normally or only args?

2024-12-20 11:30 UTC, nabriis commented on cuqi/experimental/geometry/_productgeometry.py
> +        """Converts parameter vector(s) into function values for each
I suggest to add something about the ordering of the geometries being important here.

2025-01-06 08:50 UTC, chaozg approved these changes
Thank you @amal-ghamdi for this very well-documented and -tested PR. I only left some tiny reminders about naming convection.

2025-01-06 08:50 UTC, chaozg commented on cuqi/experimental/geometry/_productgeometry.py
> +    represents the product space of multiple geometries of type Geometry.
```suggestion
    represents the product space of multiple geometries of type :class:`Geometry`.
```

2025-01-06 08:50 UTC, chaozg commented on cuqi/experimental/geometry/_productgeometry.py
> +        return tuple(fun_list)
What about `funvals` to keep consistent with `fun2par`?
```suggestion
        funvals = []
        for i, g in enumerate(self.geometries):
            funval_i = g.par2fun(args[i])
            funvals.append(funval_i)
        return tuple(funvals)
```

2025-01-06 08:50 UTC, chaozg commented on cuqi/experimental/geometry/_productgeometry.py
> +        fun_values = []
A tiny reminder that the naming conventions are different here: `funvec` and `fun_values`. Just a reminder and it's up to you if you want to keep them consistent : )

2025-01-06 08:50 UTC, chaozg commented on cuqi/experimental/geometry/_productgeometry.py
> +            vec_values.append(g.fun2vec(fun[i]))
Also naming convection here. And even tinier reminder: `fun` or `funs` to indicate that it's collection of functions?

2025-01-08 06:46 UTC, amal-ghamdi commented on cuqi/experimental/geometry/_productgeometry.py
> +        """Representation of the product geometry."""
done 👍

2025-01-08 06:47 UTC, amal-ghamdi commented on cuqi/experimental/geometry/_productgeometry.py
> +        List of geometries to be combined into a product geometry.
Thank you, updated 👍

2025-01-08 06:47 UTC, amal-ghamdi commented on cuqi/experimental/geometry/_productgeometry.py
> +        self.geometries = geometries
Error handling added 👍

2025-01-08 06:48 UTC, amal-ghamdi commented on cuqi/experimental/geometry/_productgeometry.py
> +    def par_dim_list(self):
Since it is documented and not editable and might be used by other classes in the future, I would like to keep it public for now

2025-01-08 06:48 UTC, amal-ghamdi commented on cuqi/experimental/geometry/_productgeometry.py
> +    def stacked_par_split_indices(self):
Since it is documented and not editable and might be used by other classes in the future, I would like to keep it public for now

2025-01-08 06:49 UTC, amal-ghamdi commented on cuqi/experimental/geometry/_productgeometry.py
> +        """Converts parameter vector(s) into function values for each
good suggestion, done

2025-01-08 06:49 UTC, amal-ghamdi commented on cuqi/experimental/geometry/_productgeometry.py
> +        fun_values = []
good suggestion, done

2025-01-08 06:50 UTC, amal-ghamdi commented on cuqi/experimental/geometry/_productgeometry.py
> +            vec_values.append(g.fun2vec(fun[i]))
Thanks, paying attention to consistency also helped fix the input for fun2vc. I needed to add * there.

2025-01-08 06:52 UTC, amal-ghamdi commented
Thank you @nabriis and @chaozg for your helpful review. I addressed your comments (@nabriis I am requesting a re-review). I also added a fix for the documentation.

2025-01-09 20:14 UTC, nabriis approved these changes
Thanks @amal-ghamdi. The updates LGTM :)

2025-01-10 04:03 UTC, merged